"""Add accepted field to Invitation

Revision ID: 6e4504c0ed67
Revises: de478394bbcb
Create Date: 2025-05-05 03:41:47.229616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e4504c0ed67'
down_revision: Union[str, None] = 'de478394bbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.alter_column('invitations', 'inviter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invitations', 'inviter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('invitations', 'accepted')
    # ### end Alembic commands ###
